spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/message-db
    username: admin
    password: admin
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: update
server:
  port: 9090